<?php
//showing an author box from the .csv files generated by Symbiostock
//this function is so big it gets its own file!
function symbiostock_csv_symbiocard_box($symbiocard_location = '', $compact = true, $id='symbiostock_author', $attribution = false){    
    
    if(empty($symbiocard_location)){
        
        $symbiocard_location = ABSPATH . '/symbiocard.csv';    
        
        if(file_exists(ABSPATH . '/symbiocard.csv')){
            
            $symbiocard_location = ABSPATH . '/symbiocard.csv';    
            
            } else {
                
            return;
                
            }
        }
    
    $author = new network_manager;
    $info = $author->csv_to_array($symbiocard_location, ',');
    
    
    $symbiocard = $info[0];    
    
    $symbiostock_categories = htmlspecialchars_decode ( maybe_unserialize( $symbiocard['symbiostock_author_categories'] ) );
    
    $symbiocard = array_map('strip_tags', $symbiocard);
    
    if( empty($symbiocard) || !is_array($symbiocard) ){
        _e('<em>Symbiocard not available...</em>', 'symbiostock');
        return;
    }
    
    foreach ($symbiocard as $key=>$value) {
        $symbiocard[$key] = stripslashes($value);
    }
    
    if($compact ==true && $attribution == true){
        $links = 'dropdown-menu';
        $btn_group = 'btn-group';
        
        //we toggle schema and markup based on which page we are on
        $schema = '';
        $creator_credits = 'author contributor copyrightHolder creator name';
        $bio = '';
        $panel_info = '';
        $panel_body = 'panel-body';
    } elseif($compact ==true && $attribution == false){
        
        $links = 'dropdown-menu';    
        $btn_group = 'btn-group';
        
        //we toggle schema and markup based on which page we are on
        $schema = '';
        $creator_credits = '';
        $bio = '';
        $panel_info = 'panel';
        $panel_body = '';
    } else {        
    
        $links = 'nav nav-list';    
        $btn_group = '';
        
        //we toggle schema and markup based on which page we are on
        $schema = 'itemtype="http://schema.org/CreativeWork"';
        $creator_credits = 'givenName name';
        $bio = 'itemprop="description"';
        $panel_info = 'panel';
        $panel_body = 'panel-body';
    }
    
        
    ?>
 
    <div <?php echo $schema; ?> class="author-bio contributor vcard <?php echo $panel_info ?>">        

        <div class="author-name panel-heading">
            <span class="panel-title" itemprop="<?php echo $creator_credits ?>" ><a class="ssref" title="<?php _e('Author', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_display_name'] ?>" href="<?php echo $symbiocard['symbiostock_author_page'] ?>"><?php echo $symbiocard['symbiostock_display_name'] ?></a></span>                   
        </div>
        
        <div class="symbiostock_author_info col-md-7 <?php echo $panel_body ?>">

            <div class="bio-container">                        
                <p <?php echo $bio; ?>><?php
                
                 if(isset($symbiocard['symbiostock_author_bio']) && !empty($symbiocard['symbiostock_author_bio'])){
                    if($compact == true && strlen($symbiocard['symbiostock_author_bio']) > 74){
                        $pos=strpos(stripslashes($symbiocard['symbiostock_author_bio']), ' ', 75);
                        $bio_text = substr($symbiocard['symbiostock_author_bio'], 0, min(max($pos,75),90) ) . '...<small><a class="ssref" title="'.__('See full author bio...', 'symbiostock').'" href="'.$symbiocard['symbiostock_author_page'].'"> '.__('[more]', 'symbiostock').'</a></small>';

                    } else {
                        if(!empty($symbiocard['symbiostock_author_bio'])):
                        $bio_text =    stripslashes($symbiocard['symbiostock_author_bio']);
                        endif;
                    }
                    echo $bio_text;
                }
                ?></p>
            </div>   
            <?php if($compact == false):
             
            if(!empty($symbiocard['symbiostock_home_location_coords'])):                
            $symbiostock_map_info = maybe_unserialize($symbiocard['symbiostock_home_location_coords']);
            endif;
            
            if(!empty($symbiostock_map_info) && is_array($symbiostock_map_info)){                
                $home_area = $symbiostock_map_info['results'][0]['formatted_address'];                
                } else {$home_area = '';}
                
                
            $symbiostock_temp_location_1_info = maybe_unserialize($symbiocard['symbiostock_temporary_location_1_info']);
                if(!empty($symbiostock_temp_location_1_info) && is_array($symbiostock_temp_location_1_info)){                
                $temp_location_1 = $symbiostock_temp_location_1_info['results'][0]['formatted_address'];                
                } else {$temp_location_1 = '';}
            $symbiostock_temp_location_2_info = maybe_unserialize($symbiocard['symbiostock_temporary_location_2_info']);
                if(!empty($symbiostock_temp_location_2_info) && is_array($symbiostock_temp_location_2_info)){                
                $temp_location_2 = $symbiostock_temp_location_2_info['results'][0]['formatted_address'];                
                } else {$temp_location_2 = '';}        
                    
            ?>
            <div id="<?php echo $id ?>" class="panel-group accordion">
                <!-- PANEL OPEN -->           
                <!--author important links-->  
                <div class="accordion-group ">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#<?php echo $id ?>" href="#collapseOne_<?php echo $id ?>"><i style="margin-right: 20px;" class="icon-expand-alt"> </i><i class="icon-link">&nbsp;</i>  <span itemprop="address"><?php _e('Author', 'symbiostock') ?> </span></a>
                    </div>
                    <div id="collapseOne_<?php echo $id ?>" class="accordion-body collapse">
                        <div class="accordion-inner">                    
                <?php endif; ?> 
                
                <div class="<?php echo $btn_group ?>">
                    <?php if($compact == true): ?>
                    <button type="button" class="btn btn-default" data-toggle="dropdown"><?php _e('info', 'symbiostock') ?></button>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    </button>
                    <?php endif; ?>
                    
                    <ul class="<?php echo $links ?>">
                        <?php if (isset($symbiocard['symbiostock_author_page']) && !empty($symbiocard['symbiostock_author_page'])): ?>
                        <li><a class="ssref" itemprop="" title="<?php _e('Author', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_display_name'] ?>" href="<?php echo $symbiocard['symbiostock_author_page'] ?>"><i class="icon-user"> </i> <?php _e(' Author Page ', 'symbiostock') ?></a></li>                
                        <?php endif; ?>
                        
                        <?php if (isset($symbiocard['symbiostock_portfolio']) && !empty($symbiocard['symbiostock_portfolio'])): ?>
                        <li><a itemprop="" class="symbiostock_num_images_link ssref" title="<?php _e('Portfolio', 'symbiostock') ?>" href="<?php echo $symbiocard['symbiostock_portfolio'] ?>"><i class="icon-search"> </i> <?php _e('Portfolio:', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_num_images'] ?> <?php _e('images.', 'symbiostock') ?></a></li>
                        <?php endif; ?>
                        
                        <?php if (isset($symbiocard['symbiostock_gallery_page']) && !empty($symbiocard['symbiostock_gallery_page'])): ?>
                        <li><a itemprop="" class="symbiostock_gallery_link ssref" title="<?php _e('Gallery', 'symbiostock') ?>" href="<?php echo $symbiocard['symbiostock_gallery_page'] ?>"><i class="icon-star"> </i> <?php _e('Gallery Page', 'symbiostock') ?></a></li>
                        <?php endif; ?>
                        
                        <?php if (isset($symbiocard['symbiostock_contact_page']) && !empty($symbiocard['symbiostock_contact_page'])): ?>
                        <li><a itemprop="" class="symbiostock_contact_author contact author ssref" title="<?php _e('Contact', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_display_name'] ?>" href="<?php echo $symbiocard['symbiostock_contact_page'] ?>"><i class="icon-envelope"> </i> <?php _e('Contact', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_first_name'] ?></a></li>
                        <?php endif; ?>
                       
                           <?php if (isset($symbiocard['symbiostock_rss']) && !empty($symbiocard['symbiostock_rss'])): ?>
                        <li><a itemprop="" class="symbiostock_author_rss ssref" href="<?php echo $symbiocard['symbiostock_rss'] ?>"><i class="icon-rss"> </i> <?php _e('Updates / RSS', 'symbiostock') ?></a></li>
                        <?php endif; ?>
                        
                        <?php if (isset($symbiocard['symbiostock_network_page']) && !empty($symbiocard['symbiostock_network_page'])): ?>
                        <li><a itemprop="" class="symbiostock_network_page ssref" href="<?php echo $symbiocard['symbiostock_network_page'] ?>"><i class="icon-sitemap"> </i> <?php _e('Network', 'symbiostock') ?></a></li>
                        <?php endif; ?>
                    </ul>           
                </div>  
                
                <?php if($compact == false): ?>
                           </div>
                    </div>
                </div>
                              
                <!--author categories-->
                <div class="symbiostock_author_categories accordion-group">                    
                    <div class="accordion-heading">
                        <div>
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#<?php echo $id ?>" href="#collapseTwo_<?php echo $id ?>"><i style="margin-right: 20px;" class="icon-expand-alt"> </i><i class="icon-reorder">&nbsp;</i>  <span itemprop="address"> <?php _e('Categories', 'symbiostock') ?> </span> </a>
                        </div>
                    </div>
                    <div id="collapseTwo_<?php echo $id ?>" class="accordion-body collapse">
                        <div class="accordion-inner">
                            <ul class="">                        
                            <?php echo $symbiostock_categories; ?> 
                            </ul>                              
                        </div>
                    </div>                   
                </div>          
                                                 
                <!--author network-->
                <div class="symbiostock_author_network accordion-group">                    
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#<?php echo $id ?>" href="#collapseThree_<?php echo $id ?>"><i style="margin-right: 20px;" class="icon-expand-alt"> </i><i class="icon-sitemap">&nbsp;</i>  <span><?php _e('Network', 'symbiostock') ?></span> </a>
                    </div>
                    <div id="collapseThree_<?php echo $id ?>" class="accordion-body collapse">
                        <div class="accordion-inner">
                        <!--network links-->
                        <?php                        
                        if(isset($symbiocard['symbiostock_networked_sites']) && !empty($symbiocard['symbiostock_networked_sites'])){
                            
                            $network_sites = unserialize($symbiocard['symbiostock_networked_sites']);
                            ?><ul class="nav nav-list"> <?php
                            foreach($network_sites as $site){
                                !empty($site['description'])?$desc = $site['description'] : $desc  = $site['address'];
                                echo '<li><a class="ssref" title="'.$desc.'" href="'.$site['address'].'"><i class="icon-user">&nbsp;</i> '.$desc.'</a></li>';
                                
                                }                            
                            }
                            ?></ul> <?php                    
                        ?>
                        </div>
                    </div>                   
                </div>  
                  
                <!--author site attributes-->
                <div class="accordion-group">
                       <div class="accordion-heading">    
                           <a class="accordion-toggle" data-toggle="collapse" data-parent="#<?php echo $id ?>" href="#collapseFour_<?php echo $id ?>"><i style="margin-right: 20px;" class="icon-expand-alt"> </i><i class="icon-book">&nbsp;</i> <span data-toggle="collapse" data-target="#symbiostock-author-attributes-toggle"><?php _e('Attributes & Symbiocard', 'symbiostock') ?></span></a>
                    </div>
                    <div id="collapseFour_<?php echo $id ?>" class="accordion-body collapse">
                        <table id="symbiostock-author-attributes-toggle" class="table table-condensed accordion-inner">
                            <thead><tr class="info"><th colspan="2"><?php _e('Author Attributes', 'symbiostock') ?></th></tr></thead>
                           
                            <?php if (isset($symbiocard['symbiostock_profession_1']) && !empty($symbiocard['symbiostock_profession_1'])): ?>
                            <tr><td><?php _e('Profession 1: ', 'symbiostock') ?></td><td itemprop="jobTitle"><?php echo $symbiocard['symbiostock_profession_1'] ?></td></tr>
                            <?php endif; ?>
                            
                            <?php if (isset($symbiocard['symbiostock_profession_2']) && !empty($symbiocard['symbiostock_profession_2'])): ?>
                            <tr><td><?php _e('Profession 2: ', 'symbiostock') ?></td><td itemprop="jobTitle"><?php echo $symbiocard['symbiostock_profession_2'] ?></td></tr>
                            <?php endif; ?>
                            
                            <?php if (isset($symbiocard['symbiostock_languages']) && !empty($symbiocard['symbiostock_languages'])): ?>
                            <tr><td><?php _e('Language(s):', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_languages'] ?></td></tr> 
                            <?php endif; ?>
                            
                            <?php if (isset($symbiocard['symbiostock_equipment']) && !empty($symbiocard['symbiostock_equipment'])): ?>                    
                            <tr><td><?php _e('Equipment:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_equipment'] ?></td></tr> 
                            <?php endif; ?>                    
                            
                            <?php if (isset($symbiocard['symbiostock_software']) && !empty($symbiocard['symbiostock_software'])): ?>                 
                            <tr><td><?php _e('Software:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_software'] ?></td></tr>
                            <?php endif; ?> 
                            
                            <?php if (isset($symbiocard['symbiostock_open_for_assignment_jobs']) && !empty($symbiocard['symbiostock_open_for_assignment_jobs'])): ?> 
                            <tr><td><?php _e('Available for<br /> Assignments: ', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_open_for_assignment_jobs'] ?></td></tr>
                            <?php endif; ?> 
                            <?php if (isset($home_area) && !empty($home_area)): ?>
                            <tr><td><?php _e('Home<br /> Location: ', 'symbiostock') ?> </td><td itemprop="address"><?php echo '<a target="_blank" title="' . $home_area . '" href="https://maps.google.com/?q='.urlencode($home_area).'">' . $home_area . '</a>'; ?></td></tr>
                            <?php endif; ?> 
                            
                            <?php if (isset($temp_location_1) && !empty($temp_location_1)): ?>
                            <tr><td><?php _e('Temporary <br /> Location 1: ', 'symbiostock') ?> </td><td><?php echo '<a target="_blank" title="' . $temp_location_1 . '" href="https://maps.google.com/?q='.urlencode($temp_location_1).'">' . $temp_location_1 . '</a>'; ?></td></tr>
                            <?php endif; ?> 
                            
                            <?php if (isset($temp_location_2) && !empty($temp_location_2)): ?>
                            <tr><td><?php _e('Temporary <br /> Location 2: ', 'symbiostock') ?> </td><td><?php echo '<a target="_blank" title="' . $temp_location_2 . '" href="https://maps.google.com/?q='.urlencode($temp_location_2).'">' . $temp_location_2 . '</a>'; ?></td></tr>
                            <?php endif; ?> 
                            
                            <thead><tr class="info"><th colspan="2"><?php _e('Site Attributes', 'symbiostock') ?></th></tr></thead>
                            
                            <?php if (isset($symbiocard['symbiostock_num_images']) && !empty($symbiocard['symbiostock_num_images'])): ?>
                            <tr><td><?php _e('# Images:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_num_images'] ?></td></tr> 
                            <?php endif; ?> 
                            
                            <?php if (isset($symbiocard['symbiostock_portfolio_focus_1']) && !empty($symbiocard['symbiostock_portfolio_focus_1'])): ?>
                            <tr><td><?php _e('Focus 1:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_portfolio_focus_1'] ?></td></tr> 
                            <?php endif; ?> 
                            
                            <?php if (isset($symbiocard['symbiostock_portfolio_focus_2']) && !empty($symbiocard['symbiostock_portfolio_focus_2'])): ?>
                            <tr><td><?php _e('Focus 2:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_portfolio_focus_2'] ?></td></tr>
                            <?php endif; ?> 
                            
                            <?php if (isset($symbiocard['symbiostock_specialty_1']) && !empty($symbiocard['symbiostock_specialty_1'])): ?>
                            <tr><td><?php _e('Specialty 1:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_specialty_1'] ?></td></tr>
                            <?php endif; ?>
                            
                            <?php if (isset($symbiocard['symbiostock_specialty_2']) && !empty($symbiocard['symbiostock_specialty_2'])): ?>
                            <tr><td><?php _e('Specialty 2:', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_specialty_2'] ?></td></tr> 
                            <?php endif; ?>                    
                                                 
                            <tr><td><?php _e('Symbiostock vsn', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_version'] ?></td></tr>
                            <tr><td><?php _e('Last update: ', 'symbiostock') ?> </td><td><?php echo $symbiocard['symbiostock_csv_generated_time'] ?></td></tr>       
                        </table>
                        <div class=row>
                        
                        <a class="btn btn-primary btn-large col-md-12" title="<?php _e('Get Symbiocard', 'symbiostock') ?>" href="<?php echo $symbiocard['symbiostock_site'].'/symbiocard.csv' ?>"><?php echo $symbiocard['symbiostock_display_name'] ?></a>
                        </div>
                    </div>
                </div>
                <!-- PANEL CLOSE -->                
            </div>
            <?php endif; ?> 
        </div>        

        <div class="symbiostock_author_avatar panel-body col-md-5">
            
            <?php      
                        
            !isset($symbiocard['symbiostock_personal_photo'])||!isset($symbiocard['symbiostock_personal_photo']) ? $avatar_img = symbiostock_IMGDIR . '/generic-user.jpg' : $avatar_img = $symbiocard['symbiostock_personal_photo'] ;
            
            ?>
            <p>
            <a class="ssref pull-right" title="<?php echo $symbiocard['symbiostock_display_name']; ?>" href="<?php echo $symbiocard['symbiostock_author_page'] ?>">          
                <img class="avatar avatar-150 thumbnail" src="<?php echo $avatar_img  ?>" alt="<?php _e('Author avatar', 'symbiostock') ?>" /> 
            </a> 
        </div>
        
        <div class="clearfix"></div>
      
    </div>
<?php    
} 
    
function symbiostock_csv_symbiocard_listing($symbiocard_location = ''){
    
    if(empty($symbiocard_location)){
        return;
        }
    
    }
function symbiostock_csv_symbiocard_network_results($symbiocard_location = ''){
    
    if(empty($symbiocard_location)){
        return;
        }
    if(!file_exists($symbiocard_location)){return;}
    
    $author = new network_manager;
    $info = $author->csv_to_array($symbiocard_location, ',');
    $symbiocard = $info[0];
    foreach ($symbiocard as $key=>$value) {
        $symbiocard[$key] = stripslashes($value);
    }
            
    ?>
<img class="network_avatar" alt="<?php echo $symbiocard['symbiostock_my_network_name']; ?>" src="<?php echo $symbiocard['symbiostock_my_network_avatar']; ?>" />            
<div class="btn-group">    
    <button type="button" class="btn btn-default" data-toggle="dropdown"><i class="icon-user"> </i> <?php echo $symbiocard['symbiostock_display_name'] ?> <?php _e(' Network Results:', 'symbiostock') ?></button>
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <colspan class="caret"></colspan>
    </button> 
   
    <ul class="dropdown-menu">
                    
        <?php if (isset($symbiocard['symbiostock_my_network_logo']) && !empty($symbiocard['symbiostock_my_network_logo'])): ?>
        <li><img class="media-object img-rounded aligncenter" alt="<?php echo $symbiocard['symbiostock_my_network_name']; ?>" src="<?php echo $symbiocard['symbiostock_my_network_logo']; ?>" /></li>                
        <li class="divider"></li>
        <?php endif; ?>        
            
        <?php if (isset($symbiocard['symbiostock_author_page']) && !empty($symbiocard['symbiostock_author_page'])): ?>
        <li><a class="ssref" itemprop="" title="<?php _e('Author', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_display_name'] ?>" href="<?php echo $symbiocard['symbiostock_author_page'] ?>"><i class="icon-user"> </i> <?php _e('Author Page', 'symbiostock') ?></a></li>                
        <?php endif; ?>
        
        <?php if (isset($symbiocard['symbiostock_portfolio']) && !empty($symbiocard['symbiostock_portfolio'])): ?>
        <li><a itemprop="" class="symbiostock_num_images_link ssref" title="<?php _e('Portfolio:', 'symbiostock') ?>" href="<?php echo $symbiocard['symbiostock_portfolio'] ?>"><i class="icon-search"> </i> <?php _e('Portfolio:', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_num_images'] ?></a></li>
        <?php endif; ?>
        
        <?php if (isset($symbiocard['symbiostock_gallery_page']) && !empty($symbiocard['symbiostock_gallery_page'])): ?>
        <li><a itemprop="" class="symbiostock_gallery_link ssref" title="<?php _e('Gallery', 'symbiostock') ?>" href="<?php echo $symbiocard['symbiostock_gallery_page'] ?>"><i class="icon-star"> </i> <?php _e('Gallery Page:', 'symbiostock') ?></a></li>
        <?php endif; ?>
        
        <?php if (isset($symbiocard['symbiostock_contact_page']) && !empty($symbiocard['symbiostock_contact_page'])): ?>
        <li><a itemprop="" class="symbiostock_contact_author contact author ssref" title="Contact <?php echo $symbiocard['symbiostock_display_name'] ?>" href="<?php echo $symbiocard['symbiostock_contact_page'] ?>"><i class="icon-envelope"> </i> <?php _e('Contact:', 'symbiostock') ?> <?php echo $symbiocard['symbiostock_first_name'] ?></a></li>
        <?php endif; ?>
       
        <?php if (isset($symbiocard['symbiostock_rss']) && !empty($symbiocard['symbiostock_rss'])): ?>
        <li><a itemprop="" class="symbiostock_author_rss ssref" href="<?php echo $symbiocard['symbiostock_rss'] ?>"><i class="icon-rss"> </i> <?php _e('Updates / RSS:', 'symbiostock') ?></a></li>
        <?php endif; ?>
        
        <?php if (isset($symbiocard['symbiostock_network_page']) && !empty($symbiocard['symbiostock_network_page'])): ?>
        <li><a itemprop="" class="symbiostock_network_page ssref" href="<?php echo $symbiocard['symbiostock_network_page'] ?>"><i class="icon-sitemap"> </i> <?php _e('Network:', 'symbiostock') ?></a></li>
        <?php endif; ?>
    </ul>           
</div>
     
    <?php
    }    
?>